name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 28123:8123
          - 29000:9000
        options: >-
          --health-cmd="wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Wait for ClickHouse
        run: |
          timeout 30s bash -c 'until wget --no-verbose --tries=1 --spider http://localhost:28123/ping; do sleep 1; done'

      - name: Initialize ClickHouse Schema
        run: |
          # Create database
          curl -X POST http://localhost:28123 --data-binary "CREATE DATABASE IF NOT EXISTS adapter_clickhouse_test"
          sleep 1

          # Create users table
          curl -X POST http://localhost:28123/adapter_clickhouse_test --data-binary "
          CREATE TABLE IF NOT EXISTS users
          (
            id String,
            name String,
            email String,
            emailVerified Nullable(DateTime64(3)),
            image Nullable(String)
          )
          ENGINE = MergeTree
          ORDER BY id"
          sleep 1

          # Create accounts table
          curl -X POST http://localhost:28123/adapter_clickhouse_test --data-binary "
          CREATE TABLE IF NOT EXISTS accounts
          (
            id String,
            userId String,
            provider String,
            type String,
            providerAccountId String,
            access_token String,
            expires_at Int64 DEFAULT 0,
            refresh_token String,
            id_token String,
            scope String,
            session_state String,
            token_type String
          )
          ENGINE = MergeTree
          ORDER BY id"
          sleep 1

          # Create sessions table
          curl -X POST http://localhost:28123/adapter_clickhouse_test --data-binary "
          CREATE TABLE IF NOT EXISTS sessions
          (
            id String,
            userId String,
            expires DateTime64(3),
            sessionToken String
          )
          ENGINE = MergeTree
          ORDER BY id"
          sleep 1

          # Create verificationToken table
          curl -X POST http://localhost:28123/adapter_clickhouse_test --data-binary "
          CREATE TABLE IF NOT EXISTS verificationToken
          (
            identifier String,
            expires DateTime64(3),
            token String
          )
          ENGINE = MergeTree
          ORDER BY (identifier, token)"
          sleep 1

          # Verify tables were created
          echo "Verifying tables..."
          curl -s http://localhost:28123/adapter_clickhouse_test --data-binary "SHOW TABLES FORMAT JSONEachRow"

      - name: Run tests
        run: pnpm test
        env:
          CLICKHOUSE_PORT: 28123

      - name: Build
        run: pnpm build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
