name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 28123:8123
          - 29000:9000
        options: >-
          --health-cmd="wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Wait for ClickHouse
        run: |
          timeout 30s bash -c 'until wget --no-verbose --tries=1 --spider http://localhost:28123/ping; do sleep 1; done'

      - name: Initialize ClickHouse Schema
        run: |
          # Create database
          curl -X POST "http://localhost:28123/?query=CREATE%20DATABASE%20IF%20NOT%20EXISTS%20adapter_clickhouse_test"
          sleep 1

          # Create users table
          curl -X POST "http://localhost:28123/?query=CREATE%20TABLE%20IF%20NOT%20EXISTS%20adapter_clickhouse_test.users%20(id%20String%2C%20name%20String%2C%20email%20String%2C%20emailVerified%20Nullable(DateTime64(3))%2C%20image%20Nullable(String))%20ENGINE%20%3D%20MergeTree%20ORDER%20BY%20id"
          sleep 1

          # Create accounts table
          curl -X POST "http://localhost:28123/?query=CREATE%20TABLE%20IF%20NOT%20EXISTS%20adapter_clickhouse_test.accounts%20(id%20String%2C%20userId%20String%2C%20provider%20String%2C%20type%20String%2C%20providerAccountId%20String%2C%20access_token%20String%2C%20expires_at%20Int64%20DEFAULT%200%2C%20refresh_token%20String%2C%20id_token%20String%2C%20scope%20String%2C%20session_state%20String%2C%20token_type%20String)%20ENGINE%20%3D%20MergeTree%20ORDER%20BY%20id"
          sleep 1

          # Create sessions table
          curl -X POST "http://localhost:28123/?query=CREATE%20TABLE%20IF%20NOT%20EXISTS%20adapter_clickhouse_test.sessions%20(id%20String%2C%20userId%20String%2C%20expires%20DateTime64(3)%2C%20sessionToken%20String)%20ENGINE%20%3D%20MergeTree%20ORDER%20BY%20id"
          sleep 1

          # Create verificationToken table
          curl -X POST "http://localhost:28123/?query=CREATE%20TABLE%20IF%20NOT%20EXISTS%20adapter_clickhouse_test.verificationToken%20(identifier%20String%2C%20expires%20DateTime64(3)%2C%20token%20String)%20ENGINE%20%3D%20MergeTree%20ORDER%20BY%20(identifier%2C%20token)"
          sleep 1

          # Verify tables were created
          echo "Verifying tables..."
          curl -X POST "http://localhost:28123/?query=SHOW%20TABLES%20FROM%20adapter_clickhouse_test%20FORMAT%20JSONEachRow"

      - name: Run tests
        run: pnpm test
        env:
          CLICKHOUSE_PORT: 28123

      - name: Build
        run: pnpm build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
